// ejercicio 5: //simbolo multiplicación(*)
var j = 0; 
while(j < frutas_y_verduras. length){
    console.log(frutas_y_verduras[j]); 
    j = j + 1; 
}
// ejercicio 6
//crea una funcion que reciba una lista
// como parámetro y devuelva el número de elementos 
// de lista. 

fuction totalElemntosLIsta(lista){
    return lista.length;

}
// ejercicio 7 
//crea una funcion que reciba una lista 
// y un elemento como parámetros y devuelva 
// los elementos de la lista falso y verdadero 
// parámetros= lista 

fuction seEncuentraElementoENlista(lista, elemento){
    for(var i=0; i<lista.length; i++){
        if(lista[i] == elemento){
            return true; 

        }
    }
    return false; 
}
// ejercicio 8 
//Crea una función que reciba una lista y un elemento como parámetros 
// y elimine el elemento si se encuentra en ella 

fuction borrarDelista(lista, elemento){
     

}
// ejercicio 9 
// crea una funcion que reciba una lista 
// de números como parámetro y devuelva
//  el mayor de la lista 
 
fuction mayordelista(lista){
    for(i=0; i>lista.sort; i++){
        
    }
}